require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ClassStructure:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 100
  AllowedPatterns:
    - !ruby/regexp /\A +(it|describe|context|shared_examples|include_examples|it_behaves_like) ["']/

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint:
  Exclude:
    - lib/generators/onesie/templates/*.rb

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - '**/*.rake'
    - 'Rakefile'
    - 'spec/**/*.rb'

RSpec:
  Language:
    Expectations:
      - assert_migration

RSpec/MultipleExpectations:
  Max: 2
RSpec/MultipleMemoizedHelpers:
  Max: 8
RSpec/NestedGroups:
  Max: 4

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
